
version: '3.6'
services:
    web:
        ports:
            - "9998"
        environment:
            HTTP_EXPOSE: ${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,4201:9998
            HTTPS_EXPOSE: ${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,9998:9998

    elasticsearch: # Elasticsearch Instance
        container_name: ddev-${DDEV_SITENAME}-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        volumes: # Persist ES data in seperate "esdata" volume
            - ./.elasticsearchBuild/data:/usr/share/elasticsearch/data
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
#        ports: # Expose Elasticsearch ports
#            - "9300:9300"
#            - "9200:9200"
